export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#005eb8",
        "outline-variant": "#adb3b5",
        "on-surface-variant": "#5a6062",
        "on-primary": "#f8f8ff",
        "surface-container-highest": "#dee3e6",
        "surface": "#f8f9fa",
        "primary-container": "#609efc",
        "inverse-surface": "#0c0f10",
        "tertiary-fixed": "#bfdef9",
        "tertiary-fixed-dim": "#b1d0ea",
        "error-dim": "#67040d",
        "error-container": "#fa746f",
        "surface-container-lowest": "#ffffff",
        "error": "#a83836",
        "on-tertiary": "#f5f9ff",
        "surface-container": "#ebeef0",
        "surface-variant": "#dee3e6",
        "secondary-fixed": "#92f6ce",
        "background": "#f8f9fa",
        "surface-container-low": "#f1f4f5",
        "on-error": "#fff7f6",
        "primary-fixed": "#609efc",
        "on-surface": "#2d3335",
        "on-secondary": "#e5fff1",
        "on-background": "#2d3335",
        "primary-fixed-dim": "#5191ee",
        "tertiary-container": "#bfdef9",
        "tertiary-dim": "#38566c",
        "on-error-container": "#6e0a12",
        "on-secondary-fixed": "#004935",
        "secondary-dim": "#005f46",
        "on-tertiary-container": "#315066",
        "surface-container-high": "#e5e9eb",
        "primary": "#005eb8",
        "primary-dim": "#0052a2",
        "on-secondary-fixed-variant": "#00694e",
        "tertiary": "#446279",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#002045",
        "on-tertiary-fixed": "#1d3d52",
        "on-tertiary-fixed-variant": "#3b5970",
        "inverse-on-surface": "#9b9d9e",
        "secondary-container": "#92f6ce",
        "secondary": "#006d51",
        "on-primary-fixed-variant": "#002957",
        "surface-dim": "#d5dbdd",
        "secondary-fixed-dim": "#84e7c1",
        "outline": "#767c7e",
        "on-secondary-container": "#005e45",
        "inverse-primary": "#609efc"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "2xl": "1rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
};
